create or replace PACKAGE ACC_ACCOUNTS_XAPI IS
   FUNCTION GET_ACCOUNT_NO(
      P_COMPANY_ID   IN NUMBER,
      P_PARENT_ID  IN NUMBER
       )RETURN NUMBER;

 PROCEDURE ADD_CLIENT_ACCOUNT(
     P_CLIENT_ID  NUMBER
   );
   
 PROCEDURE ADD_PROVIDER_ACCOUNT(
     P_PROVIDER_ID  NUMBER
   );
END ACC_ACCOUNTS_XAPI;