REM INSERTING into ACC_COST_CENTER
SET DEFINE OFF;
Insert into ACC_COST_CENTER (COST_CTR_ID,COST_CTR_NAME,COST_CTR_PARENT,COST_CTR_LEVEL,IS_SUB_COST_CTR,CREATED_AT,COST_CTR_STATUS,COMPANY_ID) values (1,'مركز تكلفة الفرع الرئيسي',null,1,0,null,1,0);
