REM INSERTING into ACL_APP_ROLE
SET DEFINE OFF;
Insert into ACL_APP_ROLE (ACL_APP_ROLE_ID,USER_ID,ROLE_ID,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID) values (21,1,2,1,null,1,to_date('27-APR-23','DD-MON-RR'),0);
Insert into ACL_APP_ROLE (ACL_APP_ROLE_ID,USER_ID,ROLE_ID,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID) values (22,1,4,1,to_timestamp('27-APR-23 05.22.24.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,0);
Insert into ACL_APP_ROLE (ACL_APP_ROLE_ID,USER_ID,ROLE_ID,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID) values (1,1,1,null,to_timestamp('30-MAR-23 01.20.21.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,to_date('16-APR-23','DD-MON-RR'),0);
Insert into ACL_APP_ROLE (ACL_APP_ROLE_ID,USER_ID,ROLE_ID,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID) values (2,21,2,null,to_timestamp('30-MAR-23 01.20.55.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,0);
Insert into ACL_APP_ROLE (ACL_APP_ROLE_ID,USER_ID,ROLE_ID,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID) values (3,23,3,null,to_timestamp('30-MAR-23 01.21.03.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,0);
