REM INSERTING into ADMIN_APP_OPERATION
SET DEFINE OFF;
Insert into ADMIN_APP_OPERATION (OPERATION_ID,OPERATION_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT) values (2,'حذف',null,null,null,to_date('18-MAR-23','DD-MON-RR'));
Insert into ADMIN_APP_OPERATION (OPERATION_ID,OPERATION_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT) values (3,'تعديل',null,to_timestamp('18-MAR-23 02.33.17.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into ADMIN_APP_OPERATION (OPERATION_ID,OPERATION_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT) values (4,'طباعة',null,to_timestamp('18-MAR-23 02.33.38.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into ADMIN_APP_OPERATION (OPERATION_ID,OPERATION_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT) values (1,'اضافة',null,null,null,to_date('18-MAR-23','DD-MON-RR'));
Insert into ADMIN_APP_OPERATION (OPERATION_ID,OPERATION_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT) values (5,'بحث',null,to_timestamp('18-MAR-23 02.33.45.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
