REM INSERTING into ADMIN_APP_INTERFACEE
SET DEFINE OFF;
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (6,'تقرير العملاء','8');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (23,'واجهة العملاء','9');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (1,'واجهة الموظفين','7');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (2,'تقرير الموظفين','6');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (3,'واجهة الموردين','3');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (4,'تقرير صلاحيات العمليات','20');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (21,'تقرير الموردين','2');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (61,'تقرير المستخدمين','4');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (24,'واجهة صلاحية العمليات','21');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (41,'واجهة الشاشات','11');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (43,'تقرير الشاشات','10');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (5,'تقرير صلاحيات العمليات','20');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (7,'تقرير الادوار','16');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (8,'واجهة الادوار','17');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (9,'تقرير ادوار المستخدمين','22');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (11,'تقرير المستخدمين','4');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (17,'تقرير العملاء','8');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (14,'واجهة الموظفين','7');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (16,'واجهة الموردين','3');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (18,'واجهة العملاء','9');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (19,'تقرير المخازن','41');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (22,'واجهة المجموعات','28');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (12,'واجهة المستخدمين','5');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (26,'واجهة الوحدات','25');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (27,'تقرير الاحجام','31');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (29,'تقرير الالوان','33');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (30,'واجهة الالوان','34');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (31,'تقرير اصناف المنتجات','35');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (32,'واجهة اصناف المنتجات','36');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (33,'تقرير ملف الاصناف','37');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (13,'تقرير الموظفين','6');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (15,'تقرير الموردين','2');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (20,'واجهة المخازن','42');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (25,'تقرير الوحدات','24');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (28,'واجهة الاحجام','32');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (10,'واجهة ادوار المستخدمين','23');
Insert into ADMIN_APP_INTERFACEE (INTERFACE_ID,INTERFACE_NAME,PAGE_ID) values (34,'واجهة ملف الاصناف','38');
