REM INSERTING into ADMIN_ERROR_MSG
SET DEFINE OFF;
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (1,'تم تنفيذ العملية بنجاح.','operation executed successfully.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (2,'عذراً، هناك بعض الاخطاء، يجب اصلاحها ثم اعادة المحاولة.','Please, there is some errors, please fix them and try again.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (3,'الاسم بالعربية مطلوب.','arabic name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (4,'الاسم بالإنجليزية مطلوب.','english name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (5,'اسم الحساب بالعربية مطلوب.','arabic account name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (6,'كود العملة بالعربي مطلوب.','arabic currency code is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (7,'اسم الوحدة بالعربي مطلوب.','arabic unit name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (8,'اسم المنتج بالعربي مطلوب.','arabic product name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (9,'الباركود مطلوب.','barcode is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (10,'يجب تحديد المجموعة الضريبية.','tax group must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (11,'قيمة الضريبة مطلوبة.','tax value is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (12,'الوحدة الاساسية مطلوبة.','default unit is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (13,'اسم المدينة بالعربي مطلوب.','arabic city name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (14,'اسم المنطقة بالعربي مطلوب.','arabic region name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (15,'تاريخ الفاتورة مطلوب.','invoice date is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (16,'تاريخ فاتورة المورد مطلوب.','provider invoice date is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (17,'تاريخ التوريد مطلوب.','store date is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (18,'تاريخ الصرف المخزني مطلوب.','stockout date is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (19,'يجب تحديد المنتج.','product must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (20,'يجب تحديد الوحدة.','unit must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (21,'يجب تحديد الدولة.','country must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (22,'يجب تحديد المدينة.','city must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (23,'يجب تحديد نوع الفاتورة.','invoice type must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (24,'يجب تحديد المورد.','provider must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (25,'يجب تحديد المخزن.','store must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (26,'يجب تحديد الخزنة.','safe must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (27,'يجب تحديد مركز التكلفة.','cost center must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (28,'يجب تحديد نوع الدفع.','payment type must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (35,'تاريخ السند مطلوب.','voucher date is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (30,'المبلغ مطلوب.','amount is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (31,'يجب تحديد الحساب.','account must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (32,'يجب ان يكون المدين يساوي الدائن.','debit must match credit.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (33,'يجب ان يكون مبلغ السند يساوي اجمالي الدائن.','voucher amount must match credit total.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (34,'يجب ان يكون مبلغ السند يساوي اجمالي المدين.','voucher amount must match debit total.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (29,'يجب تحديد العميل.','Client must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (50,'يجب تحديد الحالة.','Status must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (51,'رقم الجوال مطلوب.','mobile no is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (52,'اسم الدور بالعربي مطلوب.','arabic role name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (53,'اسم الدور بالانجليزي مطلوب.','english role name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (54,'يجب تحديد الفرع.','branch must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (55,'يجب تحديد اسم المخزن.','store name must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (56,'يجب تحديداظهار لكل الفروع.','For All Branches must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (57,'اسم الصندوق بالعربي مطلوب.','arabic safe name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (58,'يجب تحديد نوع المستخدم.','user type must be selected.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (59,'اسم المستخدم مطلوب.','user name is required.');
Insert into ADMIN_ERROR_MSG (MSG_ID,MSG_TEXT_AR,MSG_TEXT_EN) values (60,'يجب تحديد قيمة المجموعة الضريبية.','tax group value must be selected.');
