--------------------------------------------------------
--  File created - Saturday-August-24-2024   
--------------------------------------------------------
@D:\SmartCode\SmartRepos\accounting-app\TYPES.sql
@D:\SmartCode\SmartRepos\accounting-app\SEQUENCES.sql
@D:\SmartCode\SmartRepos\accounting-app\TABLES.sql
@D:\SmartCode\SmartRepos\accounting-app\VIEWS.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_ACCOUNTS_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_CASH_ACCOUNTS_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_COST_CENTER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_JOURNAL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_JOURNAL_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_LEDGER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_VOUCHER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACC_VOUCHER_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACL_APP_INTERFACE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACL_APP_ROLE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACL_INTERFACE_OPR_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACL_SAFE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ACL_STORE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_APP_INTERFACE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_APP_INTERFACEE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_APP_OPERATION_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_COMPANY_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_ERROR_MSG_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_INTERFACE_OPR_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_LIST_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_LIST_ITEM_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_PWD_HMAC_KEY_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_CLIENT_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_INV_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_INV_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PRODUCT_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PRODUCT_BARCODES_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PRODUCT_FILES_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PRODUCT_UNIT_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PROVIDER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PURCHASE_INV_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PURCHASE_INV_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PURCHASE_ORDER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PURCHASE_ORDER_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PUR_RETURN_INV_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_PUR_RETURN_INV_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_RENT_INV_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_RENT_INV_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_RETURN_INV_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_RETURN_INV_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_APP_ROLE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_APP_USER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_BANK_EXT_ACC_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_BRANCH_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_CITY_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_COUNTRY_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_CURRENCY_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_PARAMS_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_PROD_GROUP_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_REGION_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_SAFE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_STORE_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_TAX_GROUP_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\SETUP_UNIT_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_FIRST_PERIOD_STOCK_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_FIRST_PERIOD_STOCK_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_STOCKIN_ORDER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_STOCKIN_ORDER_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_STOCKOUT_ORDER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_STOCKOUT_ORDER_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_TRANSFER_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\STORE_TRANSFER_DTL_DATA_TABLE.sql
@D:\SmartCode\SmartRepos\accounting-app\ADMIN_COMPANY_R_DATA_VIEW.sql
@D:\SmartCode\SmartRepos\accounting-app\SALES_INV_R_DATA_VIEW.sql
@D:\SmartCode\SmartRepos\accounting-app\INDEXES.sql
@D:\SmartCode\SmartRepos\accounting-app\TRIGGERS.sql
@D:\SmartCode\SmartRepos\accounting-app\PROCEDURES.sql
@D:\SmartCode\SmartRepos\accounting-app\PACKAGES.sql
@D:\SmartCode\SmartRepos\accounting-app\PACKAGE_BODIES.sql
@D:\SmartCode\SmartRepos\accounting-app\FUNCTIONS.sql
@D:\SmartCode\SmartRepos\accounting-app\CONSTRAINTS.sql
@D:\SmartCode\SmartRepos\accounting-app\REF_CONSTRAINTS.sql
