REM INSERTING into SALES_PRODUCT_UNIT
SET DEFINE OFF;
Insert into SALES_PRODUCT_UNIT (PRODUCT_UNIT_ID,PRODUCT_ID,UNIT_ID,UNIT_VALUE,PURCHASE_PRICE,SELL_PRICE,BARCODE,COMPANY_ID) values (21,null,null,null,null,null,null,0);
Insert into SALES_PRODUCT_UNIT (PRODUCT_UNIT_ID,PRODUCT_ID,UNIT_ID,UNIT_VALUE,PURCHASE_PRICE,SELL_PRICE,BARCODE,COMPANY_ID) values (1,3,2,12,240,360,null,0);
