REM INSERTING into SALES_PRODUCT_BARCODES
SET DEFINE OFF;
Insert into SALES_PRODUCT_BARCODES (PRODUCT_BARCODE_ID,PRODUCT_ID,BARCODE,COMPANY_ID) values (21,3,'33',0);
Insert into SALES_PRODUCT_BARCODES (PRODUCT_BARCODE_ID,PRODUCT_ID,BARCODE,COMPANY_ID) values (1,3,'22',0);
Insert into SALES_PRODUCT_BARCODES (PRODUCT_BARCODE_ID,PRODUCT_ID,BARCODE,COMPANY_ID) values (3,3,'11',0);
