REM INSERTING into SALES_PRODUCT_FILES
SET DEFINE OFF;
Insert into SALES_PRODUCT_FILES (FILE_ID,FILE_PATH,FILE_MIME_TYPE,FILE_SIZE,IS_THUMBNAIL,PRODUCT_ID) values (41,'Logo-saudi-vision-2030-download-free-PNG.png','image/png','922725',null,41);
Insert into SALES_PRODUCT_FILES (FILE_ID,FILE_PATH,FILE_MIME_TYPE,FILE_SIZE,IS_THUMBNAIL,PRODUCT_ID) values (27,'Personal-info.png','image/png','185089',null,3);
