REM INSERTING into SALES_PRODUCT
SET DEFINE OFF;
Insert into SALES_PRODUCT (PRODUCT_ID,PRODUCT_NAME_AR,PRODUCT_NAME_EN,BARCODE,TYPE_ID,TAX_GROUP_ID,TAX_VALUE,DEFAULT_UNIT_ID,PRODUCT_GROUP_ID,PURCHASE_PRICE,SELL_PRICE,PROVIDER_ID,PRODUCT_STATUS,COMPANY_ID) values (41,'قميص ولادي','T-SHIRT','100',1,1,15,1,1,30,40,1,1,0);
Insert into SALES_PRODUCT (PRODUCT_ID,PRODUCT_NAME_AR,PRODUCT_NAME_EN,BARCODE,TYPE_ID,TAX_GROUP_ID,TAX_VALUE,DEFAULT_UNIT_ID,PRODUCT_GROUP_ID,PURCHASE_PRICE,SELL_PRICE,PROVIDER_ID,PRODUCT_STATUS,COMPANY_ID) values (3,'بناطيل ولادي','Boys Trousers','1',1,1,15,1,1,20,30,1,1,0);
