REM INSERTING into SALES_INV_R
SET DEFINE OFF;
Insert into SALES_INV_R (INVOICE_NO,INV_TYPE_AR,INV_TYPE_EN,C_NAME,U_NAME,PRE_TAX_AMOUNT,TOTAL_DIS,POST_DIS_AMOUNT,TOTAL_VAT,INV_AMOUNT,INVOICE_DATE,INVOICE_ID,QR_CODE) values (1,'فاتورة نقدية الدفع نقد','Invoice Cash Paied Cash','مسرة طيبة','aalrabyee',26.087,0,26.087,3.913,30,to_timestamp('11-AUG-24 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),2,'AQ5NYXNhcmF0IFRhaWJhaAIPMzEwMjg4NzA5MjAwMDAzAxQyMDI0LTA4LTI0VDIzOjU2OjA0WgQCMzAFBDMuOTE=');
