REM INSERTING into SETUP_CITY
SET DEFINE OFF;
Insert into SETUP_CITY (CITY_ID,CITY_NAME_AR,CITY_NAME_EN,COUNTRY_ID,STATUS,COMPANY_ID) values (1,'الرياض','Riyadh',1,null,0);
Insert into SETUP_CITY (CITY_ID,CITY_NAME_AR,CITY_NAME_EN,COUNTRY_ID,STATUS,COMPANY_ID) values (2,'جدة','Jeddah',1,null,0);
Insert into SETUP_CITY (CITY_ID,CITY_NAME_AR,CITY_NAME_EN,COUNTRY_ID,STATUS,COMPANY_ID) values (21,null,null,null,null,0);
