REM INSERTING into SETUP_SAFE
SET DEFINE OFF;
Insert into SETUP_SAFE (SAFE_ID,SAFE_NAME_AR,BRANCH_ID,ACCOUNT_ID,NOTE,IS_DEFAULT,FOR_ALL_BRANCHES,STATUS,COMPANY_ID,SAFE_NAME_EN) values (1,'الخزنة الرئيسية',null,101001001001,null,0,1,0,0,null);
