REM INSERTING into SETUP_REGION
SET DEFINE OFF;
Insert into SETUP_REGION (REGION_ID,REGION_NAME_AR,REGION_NAME_EN,COUNTRY_ID,CITY_ID,STATUS,COMPANY_ID) values (2,'العليا','Olya',1,1,null,0);
Insert into SETUP_REGION (REGION_ID,REGION_NAME_AR,REGION_NAME_EN,COUNTRY_ID,CITY_ID,STATUS,COMPANY_ID) values (22,null,null,null,null,null,0);
Insert into SETUP_REGION (REGION_ID,REGION_NAME_AR,REGION_NAME_EN,COUNTRY_ID,CITY_ID,STATUS,COMPANY_ID) values (1,'الرياض','Riyadh',1,1,null,0);
