REM INSERTING into SETUP_APP_ROLE
SET DEFINE OFF;
Insert into SETUP_APP_ROLE (ROLE_ID,ROLE_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID,ROLE_NAME_EN) values (1,'مدير نظام',null,to_timestamp('18-MAR-23 03.05.09.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into SETUP_APP_ROLE (ROLE_ID,ROLE_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID,ROLE_NAME_EN) values (3,'امين مخازن',null,to_timestamp('18-MAR-23 03.05.31.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into SETUP_APP_ROLE (ROLE_ID,ROLE_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID,ROLE_NAME_EN) values (2,'محاسب',null,to_timestamp('18-MAR-23 03.05.21.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into SETUP_APP_ROLE (ROLE_ID,ROLE_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID,ROLE_NAME_EN) values (4,'صندوق',null,to_timestamp('18-MAR-23 03.05.38.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null,null);
Insert into SETUP_APP_ROLE (ROLE_ID,ROLE_NAME,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,COMPANY_ID,ROLE_NAME_EN) values (5,'admin',1,to_timestamp('11-AUG-24 04.06.39.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,0,'admin');
