REM INSERTING into SETUP_APP_USER
SET DEFINE OFF;
Insert into SETUP_APP_USER (USER_ID,USER_NAME,PASS,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,STATUS,USER_TYPE,COMPANY_ID,PREFERED_LANG_ID) values (1,'aalrabyee','aalrabyee',null,to_timestamp('11-MAR-23 07.15.07.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),1,to_date('11-AUG-24','DD-MON-RR'),1,1,0,1);
Insert into SETUP_APP_USER (USER_ID,USER_NAME,PASS,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,STATUS,USER_TYPE,COMPANY_ID,PREFERED_LANG_ID) values (21,'mahmoud','mahmoud',null,to_timestamp('13-MAR-23 02.32.56.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,1,null,null,1);
Insert into SETUP_APP_USER (USER_ID,USER_NAME,PASS,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,STATUS,USER_TYPE,COMPANY_ID,PREFERED_LANG_ID) values (23,'khaled','khaled',null,to_timestamp('14-MAR-23 01.52.39.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,0,null,null,1);
Insert into SETUP_APP_USER (USER_ID,USER_NAME,PASS,CREATED_BY,CREATED_AT,MODIFIED_BY,MODIFIED_AT,STATUS,USER_TYPE,COMPANY_ID,PREFERED_LANG_ID) values (2,'AALRABYEE','aal@2023',1,to_timestamp('11-AUG-24 04.08.45.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,1,1,0,null);
