REM INSERTING into STORE_STOCKIN_ORDER
SET DEFINE OFF;
Insert into STORE_STOCKIN_ORDER (ORDER_ID,STORE_ID,ORDER_DATE,REF_ID,ACCOUNT_ID,COST_CTR_ID,ACCOUNTABLE,NOTES,COMPANY_ID,USER_ID,TOTAL_AMOUNT,ACC_JOURNAL_ID,ORDER_NO) values (1,1,to_timestamp('05-AUG-24 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null,1,0,null,0,1,20,null,null);
