--------------------------------------------------------
--  DDL for View ADMIN_COMPANY_R
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "ADMIN_COMPANY_R" ("COMPANY_ID", "NAME_AR", "NAME_EN", "TAX_NO", "FAX", "COMERCIAL_REC_NO", "TEL_NO", "MOBILE_NO", "SREET", "LOGO") AS 
  SELECT 
com.COMPANY_ID,
com.NAME_AR,
com.NAME_EN,
	com.TAX_NO,
	com.fax,
	com.COMERCIAL_REC_NO,
	com.TEL_NO,
	com.MOBILE_NO,
	com.SREET,
	'http://localhost:8000/ords/accounting/trade_v1/get_file?p_mime_type=image/png&p_file_name=Logo-saudi-vision-2030-download-free-PNG.png'  as logo
   --'https://h.top4top.io/p_2104tstpj1.png' AS logo
FROM ADMIN_COMPANY com
;
--------------------------------------------------------
--  DDL for View SALES_INV_R
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SALES_INV_R" ("INVOICE_NO", "INV_TYPE_AR", "INV_TYPE_EN", "C_NAME", "C_TAX_NO", "STORE_DATE", "C_MOBILE_NO", "C_STREET", "U_NAME", "PRE_TAX_AMOUNT", "TOTAL_DIS", "POST_DIS_AMOUNT", "TOTAL_VAT", "INV_AMOUNT", "INVOICE_DATE", "INVOICE_TIME", "INVOICE_ID", "QR_CODE", "TRANS_TYPE_AR", "TRANS_TYPE_EN", "INVOICE_TYPE", "PAYMENT_TYPE") AS 
  SELECT
    INVOICE_NO,
    (
SELECT
    'فاتورة ' ||  ITEM_NOTE_AR  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
      'الدفع ' ||    ITEM_NOTE_AR INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE) INV_TYPE_AR ,

(
SELECT
     'Invoice '  ||   ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
    'Paied ' ||  ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)INV_TYPE_EN ,
    C.NAME_AR C_NAME,
	 NVL(C.TAX_NO,'') C_TAX_NO,
    to_char(INV.STORE_DATE,'dd-MM-yyyy') STORE_DATE,
    NVL(C.MOBILE_NO,'') C_MOBILE_NO,
    NVL(C.SREET,'') C_STREET,
    U.USER_NAME U_NAME,
    PRE_TAX_TOTAL_AMOUNT PRE_TAX_AMOUNT,
    TOTAL_DISCOUNT TOTAL_DIS,
    POST_DISCOUNT_TOTAL_AMOUNT POST_DIS_AMOUNT,
    TOTAL_VAT,
    INVOICE_TOTAL_AMOUNT INV_AMOUNT,
    to_char(INV.INVOICE_DATE,'dd-MM-yyyy') INVOICE_DATE,
    TO_CHAR(INVOICE_DATE,'HH24:MI:SS') INVOICE_TIME,
    INVOICE_ID,
GET_QR_CODE(
    P_COMPANY_ID          => INV.COMPANY_ID,
    P_INVOICE_DATE        => INV.INVOICE_DATE,
    P_INV_TOTAL_WITH_VAT  => INV.INVOICE_TOTAL_AMOUNT,
    P_VAT_TOTAL           => INV.TOTAL_VAT
) QR_CODE,
'بيع' TRANS_TYPE_AR,
'Sale' TRANS_TYPE_EN,
INVOICE_TYPE,
PAYMENT_TYPE
FROM
    SALES_INV INV left JOIN SALES_CLIENT C ON INV.CLIENT_ID = C.CLIENT_ID
    LEFT JOIN SETUP_APP_USER U ON U.USER_ID = INV.USER_ID
;
--------------------------------------------------------
--  DDL for View SALES_PURCHASE_INV_R
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SALES_PURCHASE_INV_R" ("INVOICE_NO", "INV_TYPE_AR", "INV_TYPE_EN", "P_NAME", "P_TAX_NO", "P_INV_DATE", "P_INV_ID", "STORE_DATE", "P_MOBILE_NO", "P_STREET", "U_NAME", "PRE_TAX_AMOUNT", "TOTAL_DIS", "POST_DIS_AMOUNT", "TOTAL_VAT", "INV_AMOUNT", "INVOICE_DATE", "INVOICE_TIME", "INVOICE_ID", "QR_CODE", "INVOICE_TYPE", "PAYMENT_TYPE") AS 
  SELECT
    INVOICE_NO,
    (
SELECT
    'فاتورة ' ||  ITEM_NOTE_AR  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
      'الدفع ' ||    ITEM_NOTE_AR INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE) INV_TYPE_AR ,
(
SELECT
     'Invoice '  ||   ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
    'Paied ' ||  ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE) INV_TYPE_EN ,
    C.NAME_AR P_NAME,
    NVL(C.TAX_NO,'') P_TAX_NO,
    to_char(INV.PROVIDER_INV_DATE,'dd-MM-yyyy') P_INV_DATE,
    NVL(PROVIDER_INV_ID,'') P_INV_ID,
    to_char(INV.STORE_DATE,'dd-MM-yyyy') STORE_DATE,
    NVL(C.MOBILE_NO,'') P_MOBILE_NO,
    NVL(C.SREET,'') P_STREET,
    U.USER_NAME U_NAME,
    PRE_TAX_TOTAL_AMOUNT PRE_TAX_AMOUNT,
    TOTAL_DISCOUNT TOTAL_DIS,
    POST_DISCOUNT_TOTAL_AMOUNT POST_DIS_AMOUNT,
    TOTAL_VAT,
    INVOICE_TOTAL_AMOUNT INV_AMOUNT,
    to_char(INV.INVOICE_DATE,'dd-MM-yyyy') INVOICE_DATE,
    TO_CHAR(INVOICE_DATE,'HH24:MI:SS') INVOICE_TIME,
    INVOICE_ID,
GET_QR_CODE(
    P_COMPANY_ID          => INV.COMPANY_ID,
    P_INVOICE_DATE        => INV.INVOICE_DATE,
    P_INV_TOTAL_WITH_VAT  => INV.INVOICE_TOTAL_AMOUNT,
    P_VAT_TOTAL           => INV.TOTAL_VAT
) QR_CODE,
INVOICE_TYPE,
PAYMENT_TYPE
FROM
    SALES_PURCHASE_INV INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID
    LEFT JOIN SETUP_APP_USER U ON U.USER_ID = INV.USER_ID
;
--------------------------------------------------------
--  DDL for View SALES_PUR_RETURN_INV_R
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SALES_PUR_RETURN_INV_R" ("INVOICE_NO", "INV_TYPE_AR", "INV_TYPE_EN", "P_NAME", "P_TAX_NO", "P_INV_DATE", "P_INV_ID", "STORE_DATE", "P_MOBILE_NO", "P_STREET", "U_NAME", "PRE_TAX_AMOUNT", "TOTAL_DIS", "POST_DIS_AMOUNT", "TOTAL_VAT", "INV_AMOUNT", "INVOICE_DATE", "INVOICE_TIME", "INVOICE_ID", "QR_CODE", "INVOICE_TYPE", "PAYMENT_TYPE") AS 
  SELECT
    INVOICE_NO,
    (
SELECT
    'فاتورة ' ||  ITEM_NOTE_AR  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
      'الدفع ' ||    ITEM_NOTE_AR INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE) INV_TYPE_AR ,
(
SELECT
     'Invoice '  ||   ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
    'Paied ' ||  ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE) INV_TYPE_EN ,
    C.NAME_AR P_NAME,
    NVL(C.TAX_NO,'') P_TAX_NO,
    to_char(INV.PROVIDER_INV_DATE,'dd-MM-yyyy') P_INV_DATE,
    NVL(PROVIDER_INV_ID,'') P_INV_ID,
    to_char(INV.STORE_DATE,'dd-MM-yyyy') STORE_DATE,
    NVL(C.MOBILE_NO,'') P_MOBILE_NO,
    NVL(C.SREET,'') P_STREET,
    U.USER_NAME U_NAME,
    PRE_TAX_TOTAL_AMOUNT PRE_TAX_AMOUNT,
    TOTAL_DISCOUNT TOTAL_DIS,
    POST_DISCOUNT_TOTAL_AMOUNT POST_DIS_AMOUNT,
    TOTAL_VAT,
    INVOICE_TOTAL_AMOUNT INV_AMOUNT,
    to_char(INV.INVOICE_DATE,'dd-MM-yyyy') INVOICE_DATE,
    TO_CHAR(INVOICE_DATE,'HH24:MI:SS') INVOICE_TIME,
    INVOICE_ID,
GET_QR_CODE(
    P_COMPANY_ID          => INV.COMPANY_ID,
    P_INVOICE_DATE        => INV.INVOICE_DATE,
    P_INV_TOTAL_WITH_VAT  => INV.INVOICE_TOTAL_AMOUNT,
    P_VAT_TOTAL           => INV.TOTAL_VAT
) QR_CODE,
INVOICE_TYPE,
PAYMENT_TYPE
FROM
    SALES_PUR_RETURN_INV INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID
    LEFT JOIN SETUP_APP_USER U ON U.USER_ID = INV.USER_ID
;
--------------------------------------------------------
--  DDL for View SALES_RETURN_INV_R
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SALES_RETURN_INV_R" ("INVOICE_NO", "INV_TYPE_AR", "INV_TYPE_EN", "C_NAME", "C_TAX_NO", "SALES_INV_ID", "STORE_DATE", "C_MOBILE_NO", "C_STREET", "U_NAME", "PRE_TAX_AMOUNT", "TOTAL_DIS", "POST_DIS_AMOUNT", "TOTAL_VAT", "INV_AMOUNT", "INVOICE_DATE", "INVOICE_TIME", "INVOICE_ID", "QR_CODE", "TRANS_TYPE_AR", "TRANS_TYPE_EN", "INVOICE_TYPE", "PAYMENT_TYPE") AS 
  SELECT
    INVOICE_NO,
    (
SELECT
    'فاتورة ' ||  ITEM_NOTE_AR  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
      'الدفع ' ||    ITEM_NOTE_AR INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE) INV_TYPE_AR ,

(
SELECT
     'Invoice '  ||   ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE)
||' '||
(
SELECT
    'Paied ' ||  ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)INV_TYPE_EN ,
    C.NAME_AR C_NAME,
    NVL(C.TAX_NO,'') C_TAX_NO,
    SALES_INV_ID,
    to_char(INV.STORE_DATE,'dd-MM-yyyy') STORE_DATE,
    NVL(C.MOBILE_NO,'') C_MOBILE_NO,
    NVL(C.SREET,'') C_STREET,
    U.USER_NAME U_NAME,
    PRE_TAX_TOTAL_AMOUNT PRE_TAX_AMOUNT,
    TOTAL_DISCOUNT TOTAL_DIS,
    POST_DISCOUNT_TOTAL_AMOUNT POST_DIS_AMOUNT,
    TOTAL_VAT,
    INVOICE_TOTAL_AMOUNT INV_AMOUNT,
    TO_CHAR(INVOICE_DATE,'HH24:MI:SS')INVOICE_DATE,
    TO_CHAR(INVOICE_DATE,'HH24:MI:SS') INVOICE_TIME,
    INVOICE_ID,
GET_QR_CODE(
    P_COMPANY_ID          => INV.COMPANY_ID,
    P_INVOICE_DATE        => INV.INVOICE_DATE,
    P_INV_TOTAL_WITH_VAT  => INV.INVOICE_TOTAL_AMOUNT,
    P_VAT_TOTAL           => INV.TOTAL_VAT
) QR_CODE,
'مردود بيع' TRANS_TYPE_AR,
'Sales Return' TRANS_TYPE_en,
INVOICE_TYPE,
PAYMENT_TYPE
FROM
    SALES_RETURN_INV INV left JOIN SALES_CLIENT C ON INV.CLIENT_ID = C.CLIENT_ID
    LEFT JOIN SETUP_APP_USER U ON U.USER_ID = INV.USER_ID
;
--------------------------------------------------------
--  DDL for View SALES_RPT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "SALES_RPT" ("C_NAME", "INV_TYPE_AR", "INV_TYPE_EN", "INVOICE_DATE", "INVOICE_NO", "POST_DIS_AMOUNT", "TOTAL_VAT", "INV_AMOUNT") AS 
  SELECT
    C_NAME,
    INV_TYPE_AR,
    INV_TYPE_EN,
    INVOICE_DATE,
    INVOICE_NO,
    POST_DIS_AMOUNT,
    TOTAL_VAT,
    INV_AMOUNT
FROM
    SALES_INV_R
;
--------------------------------------------------------
--  DDL for View STORE_FIRST_PERIOD_STOCK_R
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "STORE_FIRST_PERIOD_STOCK_R" ("INVOICE_NO", "INV_TYPE_AR", "INV_TYPE_EN", "P_NAME", "P_TAX_NO", "P_INV_DATE", "P_INV_ID", "STORE_DATE", "P_MOBILE_NO", "P_STREET", "U_NAME", "PRE_TAX_AMOUNT", "TOTAL_DIS", "TOTAL_VAT", "POST_DIS_AMOUNT", "INV_AMOUNT", "INVOICE_DATE", "INVOICE_TIME", "INVOICE_ID", "QR_CODE", "INVOICE_TYPE") AS 
  SELECT
    INVOICE_NO,
    (
SELECT
    'فاتورة ' ||  ITEM_NOTE_AR  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INV_TYPE_AR ,
(
SELECT
     'Invoice '  ||   ITEM_NOTE_EN  INV_TYPE
FROM
    ADMIN_LIST_ITEM
WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INV_TYPE_EN ,
    C.NAME_AR P_NAME,
    NVL(C.TAX_NO,'') P_TAX_NO,
    to_char(INV.PROVIDER_INV_DATE,'dd-MM-yyyy') P_INV_DATE,
    NVL(PROVIDER_INV_ID,'') P_INV_ID,
    to_char(INV.STORE_DATE,'dd-MM-yyyy') STORE_DATE,
    NVL(C.MOBILE_NO,'') P_MOBILE_NO,
    NVL(C.SREET,'') P_STREET,
    U.USER_NAME U_NAME,
    INVOICE_TOTAL_AMOUNT PRE_TAX_AMOUNT,
    0 TOTAL_DIS,
    0 TOTAL_VAT,
    INVOICE_TOTAL_AMOUNT POST_DIS_AMOUNT,
    INVOICE_TOTAL_AMOUNT INV_AMOUNT,
    to_char(INV.INVOICE_DATE,'dd-MM-yyyy') INVOICE_DATE,
    TO_CHAR(INVOICE_DATE,'HH24:MI:SS') INVOICE_TIME,
    INVOICE_ID,
GET_QR_CODE(
    P_COMPANY_ID          => INV.COMPANY_ID,
    P_INVOICE_DATE        => INV.INVOICE_DATE,
    P_INV_TOTAL_WITH_VAT  => INV.INVOICE_TOTAL_AMOUNT,
    P_VAT_TOTAL           => 0
) QR_CODE,
INVOICE_TYPE
FROM
    STORE_FIRST_PERIOD_STOCK INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID
    LEFT JOIN SETUP_APP_USER U ON U.USER_ID = INV.USER_ID
;
