-- Generated by Oracle SQL Developer REST Data Services 20.2.0.175.1842
-- Exported REST Definitions from ORDS Schema Version 24.2.2.r1871943
-- Schema: ACCOUNTING   Date: Sun Oct 13 06:12:09 AST 2024
--
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'invoices',
      p_base_path      => '/invoices/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'pur_return_invoice',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'pur_return_invoice',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_INVOICE_ID    NUMBER;
    V_RESPONSE      CLOB;
BEGIN
    V_RESPONSE := GET_PUR_RETURN_INVOICE(
        P_FIRST       => :p_first,
        P_LAST        => :p_last,
        P_NEXT        => :p_next,
        P_PREV        => :p_prev,
        P_INVOICE_ID  => :p_invoice_id
    );
    owa_util.mime_header (''application/json'', true);
    htp.p(V_RESPONSE);

END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'pur_return_invoice',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE	
	V_INVOICE_NO                     SALES_PUR_RETURN_INV.INVOICE_NO%TYPE;
	V_INVOICE_ID                     SALES_PUR_RETURN_INV.INVOICE_ID%TYPE;
    V_TOKEN                          VARCHAR2(2000);
    -----------------------------------------------------------------------------
    V_DTL_ID                         SALES_PUR_RETURN_INV_DTL.DTL_ID%TYPE;
    V_PRODUCT_ID                     SALES_PUR_RETURN_INV_DTL.PRODUCT_ID%TYPE;
    -----------------------------------------------------------------------------
    L_BODY_OBJ                       JSON_OBJECT_T;
    L_ITEMS_ARR                      JSON_ARRAY_T;
    L_ITEM_OBJ                       JSON_OBJECT_T;
    P_VALID_RESULT                   JSON_OBJECT_T;
    -----------------------------------------------------------------------------
BEGIN
    V_TOKEN := :token;
    INSERT INTO API_LOG (
        API,
        REQ_BODY
    ) VALUES (
        ''pur_return_invoice'',
        V_TOKEN
    );
    COMMIT;
    L_BODY_OBJ := JSON_OBJECT_T(:body);
    -- step 2: call the procedure to validate inputs
    DATA_VALIDATION.PUR_RETURN_INV_VALIDATE(
        P_DATA => L_BODY_OBJ,
        P_LANG => 2,
        P_RESULT => P_VALID_RESULT
    );
    IF P_VALID_RESULT.GET_STRING(''status'') = ''failed'' THEN
        owa_util.mime_header (''application/json'', true); 
        P_VALID_RESULT.put(''data-not-valid'',''true'');
        htp.p(P_VALID_RESULT.stringify);
        return;
    END IF;
    V_INVOICE_ID := L_BODY_OBJ.GET_STRING(''invoice_id'');
    BEGIN
        IF NVL(V_INVOICE_ID,0) = 0 THEN
            SALES_PUR_RETURN_INV_TAPI.INS(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_PROVIDER_ID                   => L_BODY_OBJ.GET_STRING(''provider_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PROVIDER_INV_ID               => L_BODY_OBJ.GET_STRING(''provider_inv_id''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_PROVIDER_INV_DATE             => TO_DATE(L_BODY_OBJ.GET_STRING(''provider_inv_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        ELSE
            SALES_PUR_RETURN_INV_TAPI.UPD(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_PROVIDER_ID                   => L_BODY_OBJ.GET_STRING(''provider_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PROVIDER_INV_ID               => L_BODY_OBJ.GET_STRING(''provider_inv_id''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_PROVIDER_INV_DATE             => TO_DATE(L_BODY_OBJ.GET_STRING(''provider_inv_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        END IF;
    END;
    L_ITEMS_ARR := L_BODY_OBJ.GET_ARRAY(''items'');
    FOR I IN 0..L_ITEMS_ARR.GET_SIZE - 1 LOOP
        L_ITEM_OBJ                := TREAT(L_ITEMS_ARR.GET(I) AS JSON_OBJECT_T);
        V_DTL_ID           		  := L_ITEM_OBJ.GET_STRING(''dtl_id'');
        IF NVL(V_DTL_ID,0) = 0 THEN
            SALES_PUR_RETURN_INV_DTL_TAPI.INS(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        ELSE
            SALES_PUR_RETURN_INV_DTL_TAPI.UPD(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_DTL_ID                     => V_DTL_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        END IF;
    END LOOP;
    COMMIT;

    :status := ''1'';

end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'pur_return_invoice',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'pur_return_invoice',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'pur_return_invoices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'pur_return_invoices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select INVOICE_ID,
       to_char(INVOICE_DATE,''dd-mm-yyyy'') INVOICE_DATE,
       STORE_DATE,
       PROVIDER_INV_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,

        C.NAME_AR PROVIDER_ID,
       INV.PROVIDER_INV_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.INVOICE_NO,
       INV.BRANCH_ID
  from SALES_PUR_RETURN_INV INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_invoice',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_invoice',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_INVOICE_ID    NUMBER;
    V_RESPONSE      CLOB;
BEGIN
    V_RESPONSE := GET_PURCHASE_INVOICE(
        P_FIRST       => :p_first,
        P_LAST        => :p_last,
        P_NEXT        => :p_next,
        P_PREV        => :p_prev,
        P_INVOICE_ID  => :p_invoice_id
    );
    owa_util.mime_header (''application/json'', true);
    htp.p(V_RESPONSE);

END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_invoice',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE	
	V_INVOICE_NO                     SALES_PURCHASE_INV.INVOICE_NO%TYPE;
	V_INVOICE_ID                     SALES_PURCHASE_INV.INVOICE_ID%TYPE;
    V_TOKEN                          VARCHAR2(2000);
    -----------------------------------------------------------------------------
    V_DTL_ID                         SALES_PURCHASE_INV_DTL.DTL_ID%TYPE;
    V_PRODUCT_ID                     SALES_PURCHASE_INV_DTL.PRODUCT_ID%TYPE;
    -----------------------------------------------------------------------------
    L_BODY_OBJ                       JSON_OBJECT_T;
    L_ITEMS_ARR                      JSON_ARRAY_T;
    L_ITEM_OBJ                       JSON_OBJECT_T;
    P_VALID_RESULT                   JSON_OBJECT_T;
    -----------------------------------------------------------------------------
BEGIN
    V_TOKEN := :token;
    INSERT INTO API_LOG (
        API,
        REQ_BODY
    ) VALUES (
        ''purchase_invoice'',
        V_TOKEN
    );
    COMMIT;
    L_BODY_OBJ := JSON_OBJECT_T(:body);
    -- step 2: call the procedure to validate inputs
    DATA_VALIDATION.PURCHASE_INV_VALIDATE(
        P_DATA => L_BODY_OBJ,
        P_LANG => 2,
        P_RESULT => P_VALID_RESULT
    );
    IF P_VALID_RESULT.GET_STRING(''status'') = ''failed'' THEN
        owa_util.mime_header (''application/json'', true); 
        P_VALID_RESULT.put(''data-not-valid'',''true'');
        htp.p(P_VALID_RESULT.stringify);
        return;
    END IF;
    V_INVOICE_ID := L_BODY_OBJ.GET_STRING(''invoice_id'');
    BEGIN
        IF NVL(V_INVOICE_ID,0) = 0 THEN
            SALES_PURCHASE_INV_TAPI.INS(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_PROVIDER_ID                   => L_BODY_OBJ.GET_STRING(''provider_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PROVIDER_INV_ID               => L_BODY_OBJ.GET_STRING(''provider_inv_id''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_PROVIDER_INV_DATE             => TO_DATE(L_BODY_OBJ.GET_STRING(''provider_inv_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        ELSE
            SALES_PURCHASE_INV_TAPI.UPD(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_PROVIDER_ID                   => L_BODY_OBJ.GET_STRING(''provider_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PROVIDER_INV_ID               => L_BODY_OBJ.GET_STRING(''provider_inv_id''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_PROVIDER_INV_DATE             => TO_DATE(L_BODY_OBJ.GET_STRING(''provider_inv_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        END IF;
    END;
    L_ITEMS_ARR := L_BODY_OBJ.GET_ARRAY(''items'');
    FOR I IN 0..L_ITEMS_ARR.GET_SIZE - 1 LOOP
        L_ITEM_OBJ                := TREAT(L_ITEMS_ARR.GET(I) AS JSON_OBJECT_T);
        V_DTL_ID           		  := L_ITEM_OBJ.GET_STRING(''dtl_id'');
        IF NVL(V_DTL_ID,0) = 0 THEN
            SALES_PURCHASE_INV_DTL_TAPI.INS(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        ELSE
            SALES_PURCHASE_INV_DTL_TAPI.UPD(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_DTL_ID                     => V_DTL_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        END IF;
    END LOOP;
    COMMIT;

    :status := ''1'';

end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'purchase_invoice',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'purchase_invoice',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_order',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_order',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_INVOICE_ID    NUMBER;
    V_RESPONSE      CLOB;
BEGIN
    V_RESPONSE := GET_PURCHASE_ORDER(
        P_FIRST       => :p_first,
        P_LAST        => :p_last,
        P_NEXT        => :p_next,
        P_PREV        => :p_prev,
        P_INVOICE_ID  => :p_invoice_id
    );
    owa_util.mime_header (''application/json'', true);
    htp.p(V_RESPONSE);

END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_order',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE	
	V_ORDER_NO                     SALES_PURCHASE_ORDER.ORDER_NO%TYPE;
	V_ORDER_ID                     SALES_PURCHASE_ORDER.ORDER_ID%TYPE;
    V_TOKEN                          VARCHAR2(2000);
    -----------------------------------------------------------------------------
    V_DTL_ID                         SALES_PURCHASE_ORDER_DTL.DTL_ID%TYPE;
    V_PRODUCT_ID                     SALES_PURCHASE_ORDER_DTL.PRODUCT_ID%TYPE;
    -----------------------------------------------------------------------------
    L_BODY_OBJ                       JSON_OBJECT_T;
    L_ITEMS_ARR                      JSON_ARRAY_T;
    L_ITEM_OBJ                       JSON_OBJECT_T;
    P_VALID_RESULT                   JSON_OBJECT_T;
    -----------------------------------------------------------------------------
BEGIN
    V_TOKEN := :token;
    INSERT INTO API_LOG (
        API,
        REQ_BODY
    ) VALUES (
        ''purchase_order'',
        V_TOKEN
    );
    COMMIT;
    L_BODY_OBJ := JSON_OBJECT_T(:body);
    -- step 2: call the procedure to validate inputs
    DATA_VALIDATION.PURCHASE_INV_VALIDATE(
        P_DATA => L_BODY_OBJ,
        P_LANG => 2,
        P_RESULT => P_VALID_RESULT
    );
    IF P_VALID_RESULT.GET_STRING(''status'') = ''failed'' THEN
        owa_util.mime_header (''application/json'', true); 
        P_VALID_RESULT.put(''data-not-valid'',''true'');
        htp.p(P_VALID_RESULT.stringify);
        return;
    END IF;
    V_ORDER_ID := L_BODY_OBJ.GET_STRING(''order_id'');
    BEGIN
        IF NVL(V_ORDER_ID,0) = 0 THEN
            SALES_PURCHASE_ORDER_TAPI.INS(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_PROVIDER_ID                   => L_BODY_OBJ.GET_STRING(''provider_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PROVIDER_INV_ID               => L_BODY_OBJ.GET_STRING(''provider_inv_id''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_ORDER_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''order_date''),''DD-MM-YYYY''),
                P_PROVIDER_INV_DATE             => TO_DATE(L_BODY_OBJ.GET_STRING(''provider_inv_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_ORDER_NO                    => V_ORDER_NO,
                P_ORDER_ID                    => V_ORDER_ID
            );
        ELSE
            SALES_PURCHASE_ORDER_TAPI.UPD(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_PROVIDER_ID                   => L_BODY_OBJ.GET_STRING(''provider_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PROVIDER_INV_ID               => L_BODY_OBJ.GET_STRING(''provider_inv_id''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_ORDER_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''order_date''),''DD-MM-YYYY''),
                P_PROVIDER_INV_DATE             => TO_DATE(L_BODY_OBJ.GET_STRING(''provider_inv_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_ORDER_NO                    => V_ORDER_NO,
                P_ORDER_ID                    => V_ORDER_ID
            );
        END IF;
    END;
    L_ITEMS_ARR := L_BODY_OBJ.GET_ARRAY(''items'');
    FOR I IN 0..L_ITEMS_ARR.GET_SIZE - 1 LOOP
        L_ITEM_OBJ                := TREAT(L_ITEMS_ARR.GET(I) AS JSON_OBJECT_T);
        V_DTL_ID           		  := L_ITEM_OBJ.GET_STRING(''dtl_id'');
        IF NVL(V_DTL_ID,0) = 0 THEN
            SALES_PURCHASE_ORDER_DTL_TAPI.INS(
                P_ORDER_ID                 => V_ORDER_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        ELSE
            SALES_PURCHASE_ORDER_DTL_TAPI.UPD(
                P_ORDER_ID                 => V_ORDER_ID,
                P_DTL_ID                     => V_DTL_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        END IF;
    END LOOP;
    COMMIT;

    :status := ''1'';

end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'purchase_order',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'purchase_order',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_orders',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'purchase_orders',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ORDER_ID,
       to_char(ORDER_DATE,''dd-mm-yyyy'') ORDER_DATE,
       to_char(STORE_DATE,''dd-mm-yyyy'')STORE_DATE,
       to_char(PROVIDER_INV_DATE,''dd-mm-yyyy'')PROVIDER_INV_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,

        C.NAME_AR PROVIDER_ID,
       INV.PROVIDER_INV_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.ORDER_NO,
       INV.BRANCH_ID
  from SALES_PURCHASE_ORDER INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'purchases_invoices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'purchases_invoices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select INVOICE_ID,
       to_char(INVOICE_DATE,''dd-mm-yyyy'') INVOICE_DATE,
       STORE_DATE,
       PROVIDER_INV_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,

        C.NAME_AR PROVIDER_ID,
       INV.PROVIDER_INV_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.INVOICE_NO,
       INV.BRANCH_ID
  from SALES_PURCHASE_INV INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'rent_invoice',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'rent_invoice',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_INVOICE_ID    NUMBER;
    V_RESPONSE      CLOB;
BEGIN
    V_RESPONSE := GET_RENT_INVOICE(
        P_FIRST       => :p_first,
        P_LAST        => :p_last,
        P_NEXT        => :p_next,
        P_PREV        => :p_prev,
        P_INVOICE_ID  => :p_invoice_id
    );
    owa_util.mime_header (''application/json'', true);
    htp.p(V_RESPONSE);

END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'rent_invoice',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE	
	V_INVOICE_NO                     SALES_RENT_INV.INVOICE_NO%TYPE;
	V_INVOICE_ID                     SALES_RENT_INV.INVOICE_ID%TYPE;
    V_TOKEN                          VARCHAR2(2000);
    -----------------------------------------------------------------------------
    V_DTL_ID                         SALES_RENT_INV_DTL.DTL_ID%TYPE;
    V_PRODUCT_ID                     SALES_RENT_INV_DTL.PRODUCT_ID%TYPE;
    -----------------------------------------------------------------------------
    L_BODY_OBJ                       JSON_OBJECT_T;
    L_ITEMS_ARR                      JSON_ARRAY_T;
    L_ITEM_OBJ                       JSON_OBJECT_T;
    P_VALID_RESULT                   JSON_OBJECT_T;
    -----------------------------------------------------------------------------
BEGIN
    V_TOKEN := :token;
    INSERT INTO API_LOG (
        API,
        REQ_BODY
    ) VALUES (
        ''rent_invoice'',
        V_TOKEN
    );
    COMMIT;
    L_BODY_OBJ := JSON_OBJECT_T(:body);
    -- step 2: call the procedure to validate inputs
    DATA_VALIDATION.SALES_RENT_INV_VALIDATE(
        P_DATA => L_BODY_OBJ,
        P_LANG => 2,
        P_RESULT => P_VALID_RESULT
    );
    IF P_VALID_RESULT.GET_STRING(''status'') = ''failed'' THEN
        owa_util.mime_header (''application/json'', true); 
        P_VALID_RESULT.put(''data-not-valid'',''true'');
        htp.p(P_VALID_RESULT.stringify);
        return;
    END IF;
    V_INVOICE_ID := L_BODY_OBJ.GET_STRING(''invoice_id'');
    BEGIN
        IF NVL(V_INVOICE_ID,0) = 0 THEN
            SALES_RENT_INV_TAPI.INS(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_CLIENT_ID                     => L_BODY_OBJ.GET_STRING(''client_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        ELSE
            SALES_RENT_INV_TAPI.UPD(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_CLIENT_ID                     => L_BODY_OBJ.GET_STRING(''client_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        END IF;
    END;
    L_ITEMS_ARR := L_BODY_OBJ.GET_ARRAY(''items'');
    FOR I IN 0..L_ITEMS_ARR.GET_SIZE - 1 LOOP
        L_ITEM_OBJ                := TREAT(L_ITEMS_ARR.GET(I) AS JSON_OBJECT_T);
        V_DTL_ID           		  := L_ITEM_OBJ.GET_STRING(''dtl_id'');
        IF NVL(V_DTL_ID,0) = 0 THEN
            SALES_RENT_INV_DTL_TAPI.INS(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        ELSE
            SALES_RENT_INV_DTL_TAPI.UPD(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_DTL_ID                     => V_DTL_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        END IF;
    END LOOP;
    COMMIT;

    :status := ''1'';

end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'rent_invoice',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'rent_invoice',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'rent_invoices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'rent_invoices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select INVOICE_ID,
       to_char(INVOICE_DATE,''dd-mm-yyyy'') INVOICE_DATE,
       STORE_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,
       C.NAME_AR PROVIDER_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.INVOICE_NO,
       INV.BRANCH_ID
  from SALES_RENT_INV INV JOIN SALES_CLIENT C ON INV.CLIENT_ID = C.CLIENT_ID'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_invoice',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_invoice',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_INVOICE_ID    NUMBER;
    V_RESPONSE      CLOB;
BEGIN
    V_RESPONSE := GET_SALE_INVOICE(
        P_FIRST       => :p_first,
        P_LAST        => :p_last,
        P_NEXT        => :p_next,
        P_PREV        => :p_prev,
        P_INVOICE_ID  => :p_invoice_id
    );
    owa_util.mime_header (''application/json'', true);
    htp.p(V_RESPONSE);

END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_invoice',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE	
	V_INVOICE_NO                     SALES_INV.INVOICE_NO%TYPE;
	V_INVOICE_ID                     SALES_INV.INVOICE_ID%TYPE;
    V_TOKEN                          VARCHAR2(2000);
    -----------------------------------------------------------------------------
    V_DTL_ID                         SALES_INV_DTL.INVOICE_DTL_ID%TYPE;
    V_PRODUCT_ID                     SALES_INV_DTL.PRODUCT_ID%TYPE;
    -----------------------------------------------------------------------------
    L_BODY_OBJ                       JSON_OBJECT_T;
    L_ITEMS_ARR                      JSON_ARRAY_T;
    L_ITEM_OBJ                       JSON_OBJECT_T;
    P_VALID_RESULT                   JSON_OBJECT_T;
    -----------------------------------------------------------------------------
BEGIN
    V_TOKEN := :token;
    INSERT INTO API_LOG (
        API,
        REQ_BODY
    ) VALUES (
        ''sale_invoice'',
        V_TOKEN
    );
    COMMIT;
    L_BODY_OBJ := JSON_OBJECT_T(:body);
    -- step 2: call the procedure to validate inputs
    DATA_VALIDATION.SALES_INV_VALIDATE(
        P_DATA => L_BODY_OBJ,
        P_LANG => 2,
        P_RESULT => P_VALID_RESULT
    );
    IF P_VALID_RESULT.GET_STRING(''status'') = ''failed'' THEN
        owa_util.mime_header (''application/json'', true); 
        P_VALID_RESULT.put(''data-not-valid'',''true'');
        htp.p(P_VALID_RESULT.stringify);
        return;
    END IF;
    V_INVOICE_ID := L_BODY_OBJ.GET_STRING(''invoice_id'');
    BEGIN
        IF NVL(V_INVOICE_ID,0) = 0 THEN
            SALES_INV_TAPI.INSERT_SALES_INV(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_CLIENT_ID                     => L_BODY_OBJ.GET_STRING(''client_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        ELSE
            SALES_INV_TAPI.UPDATE_SALES_INV(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_CLIENT_ID                     => L_BODY_OBJ.GET_STRING(''client_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        END IF;
    END;
    L_ITEMS_ARR := L_BODY_OBJ.GET_ARRAY(''items'');
    FOR I IN 0..L_ITEMS_ARR.GET_SIZE - 1 LOOP
        L_ITEM_OBJ                := TREAT(L_ITEMS_ARR.GET(I) AS JSON_OBJECT_T);
        V_DTL_ID           		  := L_ITEM_OBJ.GET_STRING(''dtl_id'');
        IF NVL(V_DTL_ID,0) = 0 THEN
            SALES_INV_DTL_TAPI.INSERT_SALES_INV_DTL(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        ELSE
            SALES_INV_DTL_TAPI.UPDATE_SALES_INV_DTL(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_INVOICE_DTL_ID             => V_DTL_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        END IF;
    END LOOP;
    COMMIT;

    :status := ''1'';

end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'sale_invoice',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'sale_invoice',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_invoices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_invoices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select INVOICE_ID,
       to_char(INVOICE_DATE,''dd-mm-yyyy'') INVOICE_DATE,
       STORE_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,
       C.NAME_AR PROVIDER_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.INVOICE_NO,
       INV.BRANCH_ID
  from SALES_INV INV JOIN SALES_CLIENT C ON INV.CLIENT_ID = C.CLIENT_ID'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_return_invoice',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_return_invoice',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_INVOICE_ID    NUMBER;
    V_RESPONSE      CLOB;
BEGIN
    V_RESPONSE := GET_SALE_RETURN_INVOICE(
        P_FIRST       => :p_first,
        P_LAST        => :p_last,
        P_NEXT        => :p_next,
        P_PREV        => :p_prev,
        P_INVOICE_ID  => :p_invoice_id
    );
    owa_util.mime_header (''application/json'', true);
    htp.p(V_RESPONSE);

END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_return_invoice',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE	
	V_INVOICE_NO                     SALES_RETURN_INV.INVOICE_NO%TYPE;
	V_INVOICE_ID                     SALES_RETURN_INV.INVOICE_ID%TYPE;
    V_TOKEN                          VARCHAR2(2000);
    -----------------------------------------------------------------------------
    V_DTL_ID                         SALES_RETURN_INV_DTL.DTL_ID%TYPE;
    V_PRODUCT_ID                     SALES_RETURN_INV_DTL.PRODUCT_ID%TYPE;
    -----------------------------------------------------------------------------
    L_BODY_OBJ                       JSON_OBJECT_T;
    L_ITEMS_ARR                      JSON_ARRAY_T;
    L_ITEM_OBJ                       JSON_OBJECT_T;
    P_VALID_RESULT                   JSON_OBJECT_T;
    -----------------------------------------------------------------------------
BEGIN
    V_TOKEN := :token;
    INSERT INTO API_LOG (
        API,
        REQ_BODY
    ) VALUES (
        ''sale_return_invoice'',
        V_TOKEN
    );
    COMMIT;
    L_BODY_OBJ := JSON_OBJECT_T(:body);
    -- step 2: call the procedure to validate inputs
    DATA_VALIDATION.SALES_RETURN_INV_VALIDATE(
        P_DATA => L_BODY_OBJ,
        P_LANG => 2,
        P_RESULT => P_VALID_RESULT
    );
    IF P_VALID_RESULT.GET_STRING(''status'') = ''failed'' THEN
        owa_util.mime_header (''application/json'', true); 
        P_VALID_RESULT.put(''data-not-valid'',''true'');
        htp.p(P_VALID_RESULT.stringify);
        return;
    END IF;
    V_INVOICE_ID := L_BODY_OBJ.GET_STRING(''invoice_id'');
    BEGIN
        IF NVL(V_INVOICE_ID,0) = 0 THEN
            SALES_RETURN_INV_TAPI.INSERT_SALES_RETURN_INV(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_CLIENT_ID                     => L_BODY_OBJ.GET_STRING(''client_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        ELSE
            SALES_RETURN_INV_TAPI.UPDATE_SALES_RETURN_INV(
                P_BANK_ACC_ID                   => L_BODY_OBJ.GET_STRING(''bank_acc_id''),
                P_PAID_AMOUNT                   => L_BODY_OBJ.GET_STRING(''paid_amount''),
                P_SAFE_ID                       => L_BODY_OBJ.GET_STRING(''safe_id''),
                P_POST_DISCOUNT_TOTAL_AMOUNT    => L_BODY_OBJ.GET_STRING(''post_discount_total_amount''),
                P_USER_ID                       => L_BODY_OBJ.GET_STRING(''user_id''),
                P_CLIENT_ID                     => L_BODY_OBJ.GET_STRING(''client_id''),
                P_TOTAL_DISCOUNT                => L_BODY_OBJ.GET_STRING(''total_discount''),
                P_NOTES                         => L_BODY_OBJ.GET_STRING(''notes''),
                P_INVOICE_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''invoice_total_amount''),
                P_INVOICE_TYPE                  => L_BODY_OBJ.GET_STRING(''invoice_type''),
                P_TOTAL_QUANTITY                => L_BODY_OBJ.GET_STRING(''total_quantity''),
                P_STORE_ID                      => L_BODY_OBJ.GET_STRING(''store_id''),
                P_PRE_TAX_TOTAL_AMOUNT          => L_BODY_OBJ.GET_STRING(''pre_tax_total_amount''),
                P_COMPANY_ID                    => L_BODY_OBJ.GET_STRING(''company_id''),
                P_PAID_BANK_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_bank_amount''),
                P_COST_CTR_ID                   => L_BODY_OBJ.GET_STRING(''cost_ctr_id''),
                P_CLIENT_DISCOUNT               => L_BODY_OBJ.GET_STRING(''client_discount''),
                P_TOTAL_VAT                     => L_BODY_OBJ.GET_STRING(''total_vat''),
                P_PAYMENT_TYPE                  => L_BODY_OBJ.GET_STRING(''payment_type''),
                P_DEFERRED_AMOUNT               => L_BODY_OBJ.GET_STRING(''deferred_amount''),
                P_PAID_CASH_AMOUNT              => L_BODY_OBJ.GET_STRING(''paid_cash_amount''),
                P_INVOICE_DATE                  => TO_DATE(L_BODY_OBJ.GET_STRING(''invoice_date''),''DD-MM-YYYY''),
                P_STORE_DATE                    => TO_DATE(L_BODY_OBJ.GET_STRING(''store_date''),''DD-MM-YYYY''),
                P_BRANCH_ID                     => L_BODY_OBJ.GET_STRING(''branch_id''),
                P_INVOICE_NO                    => V_INVOICE_NO,
                P_INVOICE_ID                    => V_INVOICE_ID
            );
        END IF;
    END;
    L_ITEMS_ARR := L_BODY_OBJ.GET_ARRAY(''items'');
    FOR I IN 0..L_ITEMS_ARR.GET_SIZE - 1 LOOP
        L_ITEM_OBJ                := TREAT(L_ITEMS_ARR.GET(I) AS JSON_OBJECT_T);
        V_DTL_ID           		  := L_ITEM_OBJ.GET_STRING(''dtl_id'');
        IF NVL(V_DTL_ID,0) = 0 THEN
            SALES_RETURN_INV_DTL_TAPI.INSERT_SALES_RETURN_INV_DTL(
                P_DTL_ID                     => V_DTL_ID,
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        ELSE
            SALES_RETURN_INV_DTL_TAPI.UPDATE_SALES_RETURN_INV_DTL(
                P_INVOICE_ID                 => V_INVOICE_ID,
                P_DTL_ID                     => V_DTL_ID,
                P_PRICE                      => L_ITEM_OBJ.GET_STRING(''base_price''),
                P_QUANTITY                   => L_ITEM_OBJ.GET_STRING(''quantity''),
                P_DISCOUNT_VALUE             => L_ITEM_OBJ.GET_STRING(''discount_value''),
                P_PRODUCT_ID                 => L_ITEM_OBJ.GET_STRING(''product_id''),
                P_PRE_DISCOUNT_VAT_VALUE     => L_ITEM_OBJ.GET_STRING(''pre_discount_vat_value''),
                P_VAT_PERCENTAGE             => L_ITEM_OBJ.GET_STRING(''vat_percentage''),
                P_TOTAL_PRICE                => L_ITEM_OBJ.GET_STRING(''total_price''),
                P_VAT_VALUE                  => L_ITEM_OBJ.GET_STRING(''vat_value''),
                P_PRODUCT_UNIT_ID            => L_ITEM_OBJ.GET_STRING(''unit_id''),
                P_DISCOUNT_PERCENTAGE        => L_ITEM_OBJ.GET_STRING(''discount_percentage''),
                P_POST_DISCOUNT_TOTAL_PRICE  => L_ITEM_OBJ.GET_STRING(''post_discount_total_price''),
                P_TOTAL_AMOUNT               => L_ITEM_OBJ.GET_STRING(''total_amount'')
            );
        END IF;
    END LOOP;
    COMMIT;

    :status := ''1'';

end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'sale_return_invoice',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'invoices',
      p_pattern            => 'sale_return_invoice',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_return_invoices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'invoices',
      p_pattern        => 'sale_return_invoices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select INVOICE_ID,
       to_char(INVOICE_DATE,''dd-mm-yyyy'') INVOICE_DATE,
       STORE_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,
       C.NAME_AR PROVIDER_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.INVOICE_NO,
       INV.BRANCH_ID
  from SALES_RETURN_INV INV JOIN SALES_CLIENT C ON INV.CLIENT_ID = C.CLIENT_ID'
      );


  COMMIT; 
END;