-- Generated by Oracle SQL Developer REST Data Services 20.2.0.175.1842hkhkjh
--hghghghgh
-- Exported REST Definitions from ORDS Schema Version 24.2.2.r1871943
-- Schema: ACCOUNTING   Date: Wed Oct 09 04:15:59 AST 2024
--
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'lists',
      p_base_path      => '/lists/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'bank_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'bank_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,1,NVL(ACC_NAME_EN,ACC_NAME_AR), NVL(ACC_NAME_AR,ACC_NAME_EN)) NAME,
    BANK_ACC_ID id
    FROM SETUP_BANK_EXT_ACC 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'bank_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'bank_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'bank_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'branch_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'branch_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,2,NVL(NAME_AR,NAME_EN),NVL(NAME_EN,NAME_AR)) NAME,
    BRANCH_ID id
    FROM SETUP_BRANCH 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'branch_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'branch_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'branch_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'cost_ctr_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'cost_ctr_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,1,NVL(COST_CTR_name_EN,COST_CTR_name_ar),NVL(COST_CTR_name_ar,COST_CTR_name_EN)) NAME,
    COST_CTR_id id
    FROM ACC_COST_CENTER 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'cost_ctr_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'cost_ctr_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'cost_ctr_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'invoice_type_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'invoice_type_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,1,ITEM_DISPLAY_EN, ITEM_DISPLAY_AR) NAME,
    ITEM_NO id
    FROM ADMIN_LIST_ITEM 
    WHERE LIST_ID = 5;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'invoice_type_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'invoice_type_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'invoice_type_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'payment_type_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'payment_type_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,1,ITEM_DISPLAY_EN, ITEM_DISPLAY_AR) NAME,
    ITEM_NO id
    FROM ADMIN_LIST_ITEM 
    WHERE LIST_ID = 4;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'payment_type_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'payment_type_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'payment_type_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'product_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'product_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,1,PRODUCT_NAME_EN,PRODUCT_NAME_AR) NAME,
    PRODUCT_ID id
    FROM SALES_PRODUCT 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'product_unit_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'product_unit_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    select decode(:p_lang_id,1,UNIT_NAME_EN,UNIT_NAME_AR) NAME, U.UNIT_ID id
    from SETUP_UNIT U,SALES_PRODUCT PU
    WHERE U.COMPANY_ID = :p_company_id AND U.UNIT_ID = PU.DEFAULT_UNIT_ID 
    AND PU.PRODUCT_ID =:p_product_id
    UNION ALL
    select decode(:p_lang_id,1,UNIT_NAME_EN,UNIT_NAME_AR) NAME, U.UNIT_ID id 
    from SETUP_UNIT U,SALES_PRODUCT_UNIT PU
    WHERE U.COMPANY_ID = :p_company_id AND U.UNIT_ID = PU.UNIT_ID AND PU.PRODUCT_ID =:p_product_id;


END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_unit_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_unit_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_unit_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'product_unit_list',
      p_method             => 'GET',
      p_name               => 'p_product_id',
      p_bind_variable_name => 'p_product_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'provider_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'provider_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,2,NVL(NAME_AR,NAME_EN),NVL(NAME_EN,NAME_AR)) NAME,
    PROVIDER_ID id
    FROM SALES_PROVIDER 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'provider_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'provider_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'provider_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'save_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'save_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,2,NVL(SAFE_NAME_AR,SAFE_NAME_EN),NVL(SAFE_NAME_EN,SAFE_NAME_AR)) NAME,
    SAFE_ID id
    FROM SETUP_SAFE 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'save_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'save_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'save_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lists',
      p_pattern        => 'store_list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lists',
      p_pattern        => 'store_list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

    open :items for
    SELECT DECODE(:p_lang_id,2,NVL(STORE_NAME_AR,STORE_NAME_EN),NVL(STORE_NAME_EN,STORE_NAME_AR)) NAME,
    STORE_ID id
    FROM SETUP_STORE 
    WHERE COMPANY_ID = :p_company_id;

END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'store_list',
      p_method             => 'GET',
      p_name               => 'items',
      p_bind_variable_name => 'items',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'RESULTSET',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'store_list',
      p_method             => 'GET',
      p_name               => 'p_company_id',
      p_bind_variable_name => 'p_company_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'lists',
      p_pattern            => 'store_list',
      p_method             => 'GET',
      p_name               => 'p_lang_id',
      p_bind_variable_name => 'p_lang_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      


  COMMIT; 
END;