-- Generated by Oracle SQL Developer REST Data Services 20.2.0.175.1842
-- Exported REST Definitions from ORDS Schema Version 24.2.2.r1871943
-- Schema: ACCOUNTING   Date: Sun Oct 06 04:59:02 AST 2024
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ACCOUNTING',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'accounting',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'trade_v1',
      p_base_path      => '/trade_v1/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'trade_v1',
      p_pattern        => 'auth',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'trade_v1',
      p_pattern        => 'auth',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    P_USERNAME               NVARCHAR2(200);
    P_USER_PREFERED_LANG     VARCHAR2(200);
    P_USER_PREFERED_LANG_ID  NUMBER;
    P_COMPANY_ID             NUMBER;
    P_USER_ID                NUMBER;
    P_TOKEN                  VARCHAR2(2000);
    P_SESSION_ID             NUMBER;
BEGIN
    IF AUTH.LOGIN (P_USERNAME => :username, P_PASSWORD => :password) THEN
        AUTH.SET_USER_INFO (  
            P_USERNAME              => :username,
            P_USER_PREFERED_LANG    => P_USER_PREFERED_LANG,
            P_USER_PREFERED_LANG_ID => P_USER_PREFERED_LANG_ID,
            P_COMPANY_ID            => P_COMPANY_ID,
            P_USER_ID               => P_USER_ID
        );

        ADMIN_USER_SESSION_TAPI.INS(
            P_USER_ID               => P_USER_ID,
            P_COMPANY_ID            => P_COMPANY_ID,
            P_USERNAME              => P_USERNAME,
            P_USER_PREFERED_LANG    => P_USER_PREFERED_LANG,
            P_USER_PREFERED_LANG_ID => P_USER_PREFERED_LANG_ID,
            P_TOKEN                 => P_TOKEN,
            P_SESSION_ID            => P_SESSION_ID
        );
        COMMIT;
        :session_id := P_SESSION_ID;
        :lang_id := P_USER_PREFERED_LANG_ID;
        :user_id := P_USER_ID;
        :company_id := P_COMPANY_ID;
        :token := P_TOKEN;
        :status := 1;
        :status_code := 200;
    ELSE
        :status := ''0'';
        :message := ''بيانات الدخول غير صحيحة.'';
        :status_code := 401;
    END IF;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'company_id',
      p_bind_variable_name => 'company_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'lang_id',
      p_bind_variable_name => 'lang_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'message',
      p_bind_variable_name => 'message',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'password',
      p_bind_variable_name => 'password',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'session_id',
      p_bind_variable_name => 'session_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'token',
      p_bind_variable_name => 'token',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'user_id',
      p_bind_variable_name => 'user_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'username',
      p_bind_variable_name => 'username',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'trade_v1',
      p_pattern        => 'get_file',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'trade_v1',
      p_pattern        => 'get_file',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select :p_mime_type,BLOB_LOAD(:p_file_name) content from dual'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'get_file',
      p_method             => 'GET',
      p_name               => 'p_file_name',
      p_bind_variable_name => 'p_file_name',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'trade_v1',
      p_pattern            => 'get_file',
      p_method             => 'GET',
      p_name               => 'p_mime_type',
      p_bind_variable_name => 'p_mime_type',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'trade_v1',
      p_pattern        => 'products',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'trade_v1',
      p_pattern        => 'products',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT
    product_Id ,
    product_Name ,
    product_Price ,
    product_Path 
FROM
    product'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'trade_v1',
      p_pattern        => 'purchases_invoices',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'trade_v1',
      p_pattern        => 'purchases_invoices',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select INVOICE_ID,
       to_char(INVOICE_DATE,''dd-mm-yyyy'') INVOICE_DATE,
       STORE_DATE,
       PROVIDER_INV_DATE,
       STORE_ID,
       (
        SELECT
           ITEM_NOTE_AR  INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 5 AND ITEM_NO = INVOICE_TYPE) INVOICE_TYPE,
       (
        SELECT
              ITEM_NOTE_AR INV_TYPE
        FROM
            ADMIN_LIST_ITEM
        WHERE LIST_ID = 4 AND ITEM_NO = PAYMENT_TYPE)PAYMENT_TYPE,
       SAFE_ID,
       COST_CTR_ID,

        C.NAME_AR PROVIDER_ID,
       INV.PROVIDER_INV_ID,
       INV.PRE_TAX_TOTAL_AMOUNT,
       INV.CLIENT_DISCOUNT,
       INV.TOTAL_DISCOUNT,
       INV.POST_DISCOUNT_TOTAL_AMOUNT,
       INV.TOTAL_VAT,
       INV.TOTAL_QUANTITY,
       INV.INVOICE_TOTAL_AMOUNT,
       INV.PAID_CASH_AMOUNT,
       INV.PAID_BANK_AMOUNT,
       INV.NOTES,
       INV.COMPANY_ID,
       INV.USER_ID,
       INV.BANK_ACC_ID,
       INV.PAID_AMOUNT,
       INV.DEFERRED_AMOUNT,
       INV.ACC_JOURNAL_ID,
       INV.INVOICE_NO,
       INV.BRANCH_ID
  from SALES_PURCHASE_INV INV JOIN SALES_PROVIDER C ON INV.PROVIDER_ID = C.PROVIDER_ID'
      );


  COMMIT; 
END;