-- Generated by Oracle SQL Developer REST Data Services 20.2.0.175.1842
-- Exported REST Definitions from ORDS Schema Version 24.2.2.r1871943
-- Schema: ACCOUNTING   Date: Tue Oct 15 12:14:18 AST 2024
--
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'utils',
      p_base_path      => '/utils/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_by_barcode',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_by_barcode',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_PRODUCT_ID NUMBER;
BEGIN

    SELECT min(PRO.PRODUCT_ID)
    INTO V_PRODUCT_ID
    FROM SALES_PRODUCT PRO LEFT JOIN SALES_PRODUCT_BARCODES CODE ON PRO.PRODUCT_ID = CODE.PRODUCT_ID
    WHERE (PRO.BARCODE = :p_barcode OR CODE.BARCODE = :p_barcode) AND PRO.COMPANY_ID = :p_company_id;
    IF V_PRODUCT_ID IS NOT NULL THEN

        WITH PROD AS (
            SELECT
                BARCODE,
                PURCHASE_PRICE PRICE_WITH_VAT,
                DEFAULT_UNIT_ID,
                TAX_VALUE VAT_PERCENTAGE,
                1 QUANTITY,
                0 DISCOUNT
            FROM
                SALES_PRODUCT
                where PRODUCT_ID  = V_PRODUCT_ID and COMPANY_ID = :p_company_id
        )
        SELECT
            V_PRODUCT_ID,
            PROD.QUANTITY,
            PROD.DEFAULT_UNIT_ID,
            BASE_PRICE,
            TOTAL_PRICE,
            PROD.DISCOUNT,
            DISCOUNT_VALUE,
            POST_DISCOUNT_TOTAL_PRICE,
            PROD.VAT_PERCENTAGE,
            VAT_VALUE,
            TOTAL_AMOUNT,
            PRE_DISCOUNT_VAT_VALUE,
            PROD.PRICE_WITH_VAT ORIGINAL_PRICE
        INTO 
            :product_id,
            :quantity,
            :unit_id,
            :base_price,
            :total_price,
            :discount,
            :discount_value,
            :post_discount_total_price,
            :vat_percentage,
            :vat_value,
            :total_amount,
            :pre_discount_vat_value,
            :original_price
        FROM PROD,TABLE(COMPUTE.CALC_INV(
            P_QUANTITY             => PROD.QUANTITY,
            P_BASE_PRICE           => 0,
            P_PRICE_WITH_VAT       => PROD.PRICE_WITH_VAT,
            P_TOTAL_PRICE          => 0,
            P_VAT_PERCENTAGE       => PROD.VAT_PERCENTAGE,
            P_DISCOUNT_PERCENTAGE  => PROD.DISCOUNT
            ));
    END IF;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'base_price',
      p_bind_variable_name => 'base_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'discount',
      p_bind_variable_name => 'discount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'discount_value',
      p_bind_variable_name => 'discount_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'original_price',
      p_bind_variable_name => 'original_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'p_barcode',
      p_bind_variable_name => 'p_barcode',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'post_discount_total_price',
      p_bind_variable_name => 'post_discount_total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'pre_discount_vat_value',
      p_bind_variable_name => 'pre_discount_vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'product_id',
      p_bind_variable_name => 'product_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'quantity',
      p_bind_variable_name => 'quantity',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'total_amount',
      p_bind_variable_name => 'total_amount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'total_price',
      p_bind_variable_name => 'total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'unit_id',
      p_bind_variable_name => 'unit_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'vat_percentage',
      p_bind_variable_name => 'vat_percentage',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_by_barcode',
      p_method             => 'GET',
      p_name               => 'vat_value',
      p_bind_variable_name => 'vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_price',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_price',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    WITH PROD AS (
        SELECT
            BARCODE,
            PURCHASE_PRICE PRICE_WITH_VAT,
            DEFAULT_UNIT_ID,
            TAX_VALUE VAT_PERCENTAGE,
            1 QUANTITY,
            0 DISCOUNT
        FROM
            SALES_PRODUCT
            where PRODUCT_ID  = :p_product_id and COMPANY_ID = :p_company_id
    )
    SELECT
        PROD.BARCODE,
        PROD.QUANTITY,
        PROD.DEFAULT_UNIT_ID,
        BASE_PRICE,
        TOTAL_PRICE,
        PROD.DISCOUNT,
        DISCOUNT_VALUE,
        POST_DISCOUNT_TOTAL_PRICE,
        PROD.VAT_PERCENTAGE,
        VAT_VALUE,
        TOTAL_AMOUNT,
        PRE_DISCOUNT_VAT_VALUE,
        PROD.PRICE_WITH_VAT ORIGINAL_PRICE
    INTO 
        :barcode,
        :quantity,
        :unit_id,
        :base_price,
        :total_price,
        :discount,
        :discount_value,
        :post_discount_total_price,
        :vat_percentage,
        :vat_value,
        :total_amount,
        :pre_discount_vat_value,
        :original_price
    FROM PROD,TABLE(COMPUTE.CALC_INV(
        P_QUANTITY             => PROD.QUANTITY,
        P_BASE_PRICE           => 0,
        P_PRICE_WITH_VAT       => PROD.PRICE_WITH_VAT,
        P_TOTAL_PRICE          => 0,
        P_VAT_PERCENTAGE       => PROD.VAT_PERCENTAGE,
        P_DISCOUNT_PERCENTAGE  => PROD.DISCOUNT
        ));
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'barcode',
      p_bind_variable_name => 'barcode',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'base_price',
      p_bind_variable_name => 'base_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'discount',
      p_bind_variable_name => 'discount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'discount_value',
      p_bind_variable_name => 'discount_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'original_price',
      p_bind_variable_name => 'original_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'post_discount_total_price',
      p_bind_variable_name => 'post_discount_total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'pre_discount_vat_value',
      p_bind_variable_name => 'pre_discount_vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'quantity',
      p_bind_variable_name => 'quantity',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'total_amount',
      p_bind_variable_name => 'total_amount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'total_price',
      p_bind_variable_name => 'total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'unit_id',
      p_bind_variable_name => 'unit_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'vat_percentage',
      p_bind_variable_name => 'vat_percentage',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_price',
      p_method             => 'GET',
      p_name               => 'vat_value',
      p_bind_variable_name => 'vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_sell_price',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_sell_price',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    WITH PROD AS (
        SELECT
            BARCODE,
            SELL_PRICE PRICE_WITH_VAT,
            DEFAULT_UNIT_ID,
            TAX_VALUE VAT_PERCENTAGE,
            1 QUANTITY,
            0 DISCOUNT
        FROM
            SALES_PRODUCT
            where PRODUCT_ID  = :p_product_id and COMPANY_ID = :p_company_id
    )
    SELECT
        PROD.BARCODE,
        PROD.QUANTITY,
        PROD.DEFAULT_UNIT_ID,
        BASE_PRICE,
        TOTAL_PRICE,
        PROD.DISCOUNT,
        DISCOUNT_VALUE,
        POST_DISCOUNT_TOTAL_PRICE,
        PROD.VAT_PERCENTAGE,
        VAT_VALUE,
        TOTAL_AMOUNT,
        PRE_DISCOUNT_VAT_VALUE,
        PROD.PRICE_WITH_VAT ORIGINAL_PRICE
    INTO 
        :barcode,
        :quantity,
        :unit_id,
        :base_price,
        :total_price,
        :discount,
        :discount_value,
        :post_discount_total_price,
        :vat_percentage,
        :vat_value,
        :total_amount,
        :pre_discount_vat_value,
        :original_price
    FROM PROD,TABLE(COMPUTE.CALC_INV(
        P_QUANTITY             => PROD.QUANTITY,
        P_BASE_PRICE           => 0,
        P_PRICE_WITH_VAT       => PROD.PRICE_WITH_VAT,
        P_TOTAL_PRICE          => 0,
        P_VAT_PERCENTAGE       => PROD.VAT_PERCENTAGE,
        P_DISCOUNT_PERCENTAGE  => PROD.DISCOUNT
        ));
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'barcode',
      p_bind_variable_name => 'barcode',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'base_price',
      p_bind_variable_name => 'base_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'discount',
      p_bind_variable_name => 'discount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'discount_value',
      p_bind_variable_name => 'discount_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'original_price',
      p_bind_variable_name => 'original_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'post_discount_total_price',
      p_bind_variable_name => 'post_discount_total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'pre_discount_vat_value',
      p_bind_variable_name => 'pre_discount_vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'quantity',
      p_bind_variable_name => 'quantity',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'total_amount',
      p_bind_variable_name => 'total_amount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'total_price',
      p_bind_variable_name => 'total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'unit_id',
      p_bind_variable_name => 'unit_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'vat_percentage',
      p_bind_variable_name => 'vat_percentage',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price',
      p_method             => 'GET',
      p_name               => 'vat_value',
      p_bind_variable_name => 'vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_sell_price_by_barcode',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_sell_price_by_barcode',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    V_PRODUCT_ID NUMBER;
BEGIN

    SELECT min(PRO.PRODUCT_ID)
    INTO V_PRODUCT_ID
    FROM SALES_PRODUCT PRO LEFT JOIN SALES_PRODUCT_BARCODES CODE ON PRO.PRODUCT_ID = CODE.PRODUCT_ID
    WHERE (PRO.BARCODE = :p_barcode OR CODE.BARCODE = :p_barcode) AND PRO.COMPANY_ID = :p_company_id;
    IF V_PRODUCT_ID IS NOT NULL THEN

        WITH PROD AS (
            SELECT
                BARCODE,
                SELL_PRICE PRICE_WITH_VAT,
                DEFAULT_UNIT_ID,
                TAX_VALUE VAT_PERCENTAGE,
                1 QUANTITY,
                0 DISCOUNT
            FROM
                SALES_PRODUCT
                where PRODUCT_ID  = V_PRODUCT_ID and COMPANY_ID = :p_company_id
        )
        SELECT
            V_PRODUCT_ID,
            PROD.QUANTITY,
            PROD.DEFAULT_UNIT_ID,
            BASE_PRICE,
            TOTAL_PRICE,
            PROD.DISCOUNT,
            DISCOUNT_VALUE,
            POST_DISCOUNT_TOTAL_PRICE,
            PROD.VAT_PERCENTAGE,
            VAT_VALUE,
            TOTAL_AMOUNT,
            PRE_DISCOUNT_VAT_VALUE,
            PROD.PRICE_WITH_VAT ORIGINAL_PRICE
        INTO 
            :product_id,
            :quantity,
            :unit_id,
            :base_price,
            :total_price,
            :discount,
            :discount_value,
            :post_discount_total_price,
            :vat_percentage,
            :vat_value,
            :total_amount,
            :pre_discount_vat_value,
            :original_price
        FROM PROD,TABLE(COMPUTE.CALC_INV(
            P_QUANTITY             => PROD.QUANTITY,
            P_BASE_PRICE           => 0,
            P_PRICE_WITH_VAT       => PROD.PRICE_WITH_VAT,
            P_TOTAL_PRICE          => 0,
            P_VAT_PERCENTAGE       => PROD.VAT_PERCENTAGE,
            P_DISCOUNT_PERCENTAGE  => PROD.DISCOUNT
            ));
    END IF;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'base_price',
      p_bind_variable_name => 'base_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'discount',
      p_bind_variable_name => 'discount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'discount_value',
      p_bind_variable_name => 'discount_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'original_price',
      p_bind_variable_name => 'original_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'p_barcode',
      p_bind_variable_name => 'p_barcode',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'post_discount_total_price',
      p_bind_variable_name => 'post_discount_total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'pre_discount_vat_value',
      p_bind_variable_name => 'pre_discount_vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'product_id',
      p_bind_variable_name => 'product_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'quantity',
      p_bind_variable_name => 'quantity',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'total_amount',
      p_bind_variable_name => 'total_amount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'total_price',
      p_bind_variable_name => 'total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'unit_id',
      p_bind_variable_name => 'unit_id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'vat_percentage',
      p_bind_variable_name => 'vat_percentage',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_sell_price_by_barcode',
      p_method             => 'GET',
      p_name               => 'vat_value',
      p_bind_variable_name => 'vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_unit_price',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_unit_price',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    WITH PROD AS (
        SELECT
            PURCHASE_PRICE PRICE_WITH_VAT,
            DEFAULT_UNIT_ID UNIT_ID,
            TAX_VALUE VAT_PERCENTAGE,
            :p_quantity QUANTITY,
            0 DISCOUNT
        FROM
            SALES_PRODUCT
            where PRODUCT_ID  = :p_product_id and COMPANY_ID = :p_company_id AND DEFAULT_UNIT_ID = :p_product_unit_id 
        UNION ALL
        SELECT
            U.PURCHASE_PRICE PRICE_WITH_VAT,
            U.UNIT_ID,
            P.TAX_VALUE VAT_PERCENTAGE,
            :p_quantity QUANTITY,
            0 DISCOUNT
        FROM
            SALES_PRODUCT_UNIT U,SALES_PRODUCT P
            where P.PRODUCT_ID = U.PRODUCT_ID 
            and U.UNIT_ID  = :p_product_unit_id 
            and P.DEFAULT_UNIT_ID <> :p_product_unit_id 
            AND U.PRODUCT_ID  = :p_product_id 
            and P.COMPANY_ID = :p_company_id
    )
    SELECT
        BASE_PRICE,
        TOTAL_PRICE,
        PROD.DISCOUNT,
        DISCOUNT_VALUE,
        POST_DISCOUNT_TOTAL_PRICE,
        PROD.VAT_PERCENTAGE,
        VAT_VALUE,
        TOTAL_AMOUNT,
        PRE_DISCOUNT_VAT_VALUE,
        PROD.PRICE_WITH_VAT ORIGINAL_PRICE

    INTO 
        :base_price,
        :total_price,
        :discount,
        :discount_value,
        :post_discount_total_price,
        :vat_percentage,
        :vat_value,
        :total_amount,
        :pre_discount_vat_value,
        :original_price
    FROM PROD,TABLE(COMPUTE.CALC_INV(
        P_QUANTITY             => PROD.QUANTITY,
        P_BASE_PRICE           => 0,
        P_PRICE_WITH_VAT       => PROD.PRICE_WITH_VAT,
        P_TOTAL_PRICE          => 0,
        P_VAT_PERCENTAGE       => PROD.VAT_PERCENTAGE,
        P_DISCOUNT_PERCENTAGE  => PROD.DISCOUNT
        ));
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'base_price',
      p_bind_variable_name => 'base_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'discount',
      p_bind_variable_name => 'discount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'discount_value',
      p_bind_variable_name => 'discount_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'original_price',
      p_bind_variable_name => 'original_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'post_discount_total_price',
      p_bind_variable_name => 'post_discount_total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'pre_discount_vat_value',
      p_bind_variable_name => 'pre_discount_vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'total_amount',
      p_bind_variable_name => 'total_amount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'total_price',
      p_bind_variable_name => 'total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'vat_percentage',
      p_bind_variable_name => 'vat_percentage',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_price',
      p_method             => 'GET',
      p_name               => 'vat_value',
      p_bind_variable_name => 'vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_unit_sell_price',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'utils',
      p_pattern        => 'get_product_unit_sell_price',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    WITH PROD AS (
        SELECT
            SELL_PRICE PRICE_WITH_VAT,
            DEFAULT_UNIT_ID UNIT_ID,
            TAX_VALUE VAT_PERCENTAGE,
            :p_quantity QUANTITY,
            0 DISCOUNT
        FROM
            SALES_PRODUCT
            where PRODUCT_ID  = :p_product_id and COMPANY_ID = :p_company_id AND DEFAULT_UNIT_ID = :p_product_unit_id 
        UNION ALL
        SELECT
            U.SELL_PRICE PRICE_WITH_VAT,
            U.UNIT_ID,
            P.TAX_VALUE VAT_PERCENTAGE,
            :p_quantity QUANTITY,
            0 DISCOUNT
        FROM
            SALES_PRODUCT_UNIT U,SALES_PRODUCT P
            where P.PRODUCT_ID = U.PRODUCT_ID 
            and U.UNIT_ID  = :p_product_unit_id 
            and P.DEFAULT_UNIT_ID <> :p_product_unit_id 
            AND U.PRODUCT_ID  = :p_product_id 
            and P.COMPANY_ID = :p_company_id
    )
    SELECT
        BASE_PRICE,
        TOTAL_PRICE,
        PROD.DISCOUNT,
        DISCOUNT_VALUE,
        POST_DISCOUNT_TOTAL_PRICE,
        PROD.VAT_PERCENTAGE,
        VAT_VALUE,
        TOTAL_AMOUNT,
        PRE_DISCOUNT_VAT_VALUE,
        PROD.PRICE_WITH_VAT ORIGINAL_PRICE

    INTO 
        :base_price,
        :total_price,
        :discount,
        :discount_value,
        :post_discount_total_price,
        :vat_percentage,
        :vat_value,
        :total_amount,
        :pre_discount_vat_value,
        :original_price
    FROM PROD,TABLE(COMPUTE.CALC_INV(
        P_QUANTITY             => PROD.QUANTITY,
        P_BASE_PRICE           => 0,
        P_PRICE_WITH_VAT       => PROD.PRICE_WITH_VAT,
        P_TOTAL_PRICE          => 0,
        P_VAT_PERCENTAGE       => PROD.VAT_PERCENTAGE,
        P_DISCOUNT_PERCENTAGE  => PROD.DISCOUNT
        ));
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'base_price',
      p_bind_variable_name => 'base_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'discount',
      p_bind_variable_name => 'discount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'discount_value',
      p_bind_variable_name => 'discount_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'original_price',
      p_bind_variable_name => 'original_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'post_discount_total_price',
      p_bind_variable_name => 'post_discount_total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'pre_discount_vat_value',
      p_bind_variable_name => 'pre_discount_vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'total_amount',
      p_bind_variable_name => 'total_amount',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'total_price',
      p_bind_variable_name => 'total_price',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'vat_percentage',
      p_bind_variable_name => 'vat_percentage',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'utils',
      p_pattern            => 'get_product_unit_sell_price',
      p_method             => 'GET',
      p_name               => 'vat_value',
      p_bind_variable_name => 'vat_value',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      


  COMMIT; 
END;